[Variables]
; Default music player locations
SpotifyPath=["%APPDATA%\Roaming\Spotify\Spotify.exe"]
iTunesPath=["C:\Program Files\iTunes\itunes.exe"]
AIMPPath=["C:\Program Files (x86)\AIMP\AIMP.exe"]
foobar2000Path=["C:\Program Files (x86)\foobar2000\foobar2000.exe"]
MediaMonkeyPath=["C:\Program Files\MediaMonkey\MediaMonkey.exe"]
MusicBeePath=["C:\Program Files\MusicBee\Musicbee.exe"]
WinampPath=["C:\ProgramFiles\Winamp\winamp.exe"]
WindowsMediaPlayerPath=["%ProgramFiles(x86)%\Windows Media Player\wmplayer.exe"]

;NowPlaying names for music players
SpotifyNowPlayingName=Spotify
iTunesNowPlayingName=iTunes
AIMPNowPlayingName=AIMP
foobar2000NowPlayingName=CAD
MediaMonkeyNowPlayingName="MediaMonkey
MusicBeeNowPlayingName=CAD
WinampNowPlayingName=Winamp
WindowsMediaPlayerNowPlayingName=WMP