[Variables]
PlayerName=Spotify
; Change this to the name of your media player
; Visit this page for all supported players: http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist

PlayerPath="%USERPROFILE%\AppData\Roaming\Spotify\Spotify.exe"
; This is the path to your media player. If it doesn't open, make sure this is correct

UseDesktopColors=1
; Uses your desktop's background colors for the text. Requires refreshing the skin to take effect.

CustomPrimaryColor=255,255,255
;If Desktop Colors are disabled, this is the color of the track and and artist

CustomSecondaryColor=128,128,128
;If Desktop Colors are disabled, this is the color of the words "NOW PLAYING"
