[ChameleonDesktop]
Measure=Plugin
Plugin=Chameleon
Type=Desktop
UpdateDivider=100

[ChameleonFG1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground1

[ChameleonBG1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background1

[ChameleonFG2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground2

[ChameleonBG2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background2

[ChameleonL1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Light1

[ChameleonL2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Light2

[ChameleonD1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Dark1

[ChameleonD2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Dark2